name: Publish Package to npmjs
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Pack package
        run: yarn pack

      - name: Publish package
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
